module.exports = {
  // FILE_NAME: "NIFTY_50_2019_2023.csv",
  FILE_NAME: "NIFTY_50_2022.csv",
  SAMPLE_SIZE: 1000,

  LOT_SIZE: 75,
  NUM_OF_LOTS: 1,
  TAX_AND_BROKERAGE_PER_TRADE: 80,

  // Nifty points
  TARGET: 200,
  STOPLOSS: -50,
  TRAILING_STOPLOSS: 75,
  TRAIL_STOPLOSS_AT_MARKET_MOVEMENT: 25,

  DAY_STOPLOSS: 0,

  NUM_OF_TRADE_IN_A_DAY: 1,
  START_DAY_TRADE_AFTER_MINUTES: 45,
  DURATION_BETWEEN_TRADES_IN_MINUTES: 5,
};
